<script setup lang="ts">
import { shallowRef, useTemplateRef } from 'vue';
import { IconifyIcon } from '@vben/icons';
import { message, Modal } from 'antdv-next';
interface Props { loading: boolean; }
defineProps<Props>(); const open = defineModel<boolean>('open', { default: false }); const emit = defineEmits<{ submit: [file: File] }>(); const dragging = shallowRef(false); const fileInputRef = useTemplateRef<HTMLInputElement>('fileInput');
function openFileDialog() { fileInputRef.value?.click(); } function submitFile(file: File | null) { if (!file) return; if (!/\.(xlsx|xlsm|xls)$/iu.test(file.name)) { message.warning('请选择 Excel 文件，支持 .xlsx、.xlsm、.xls 格式'); return; } emit('submit', file); } function handleFileInput(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0] ?? null; input.value = ''; submitFile(file); } function handleDrop(event: DragEvent) { dragging.value = false; submitFile(event.dataTransfer?.files?.[0] ?? null); }
</script>
<template><Modal v-model:open="open" :footer="null" title="导入员工名册" width="560px"><div class="employee-import-upload"><button class="employee-import-upload__dropzone" :class="{ 'employee-import-upload__dropzone--dragging': dragging }" type="button" @click="openFileDialog" @dragenter.prevent="dragging = true" @dragover.prevent="dragging = true" @dragleave.prevent="dragging = false" @drop.prevent="handleDrop"><IconifyIcon class="employee-import-upload__icon" icon="lucide:file-up" /><strong>选择或拖入员工花名册</strong><span>系统会先校验并展示预览，确认后才写入企业员工资料。</span></button><input ref="fileInput" accept=".xlsx,.xlsm,.xls" class="employee-import-upload__input" type="file" @change="handleFileInput" /><span v-if="loading" class="employee-import-upload__hint">正在解析员工花名册...</span></div></Modal></template>
<style scoped>.employee-import-upload { display: grid; gap: 12px; }.employee-import-upload__dropzone { display: grid; min-height: 176px; place-items: center; gap: 8px; padding: 20px; color: #374151; text-align: center; cursor: pointer; background: #f9fafb; border: 1px dashed #9ca3af; border-radius: 6px; }.employee-import-upload__dropzone--dragging { background: #eff6ff; border-color: #2563eb; }.employee-import-upload__icon { width: 30px; height: 30px; color: #2563eb; }.employee-import-upload__dropzone span,.employee-import-upload__hint { color: #6b7280; }.employee-import-upload__input { display: none; }</style>
