<script setup lang="ts">
import type { EnterpriseWorkspaceEmployeeImportAction, EnterpriseWorkspaceEmployeeImportPreview, EnterpriseWorkspaceEmployeeImportPreviewRow } from '#/api';
import { computed, shallowRef, watch } from 'vue';
import { Alert, Button, Modal, Statistic, Tag } from 'antdv-next';
interface Props { loading: boolean; preview?: EnterpriseWorkspaceEmployeeImportPreview; }
const props = defineProps<Props>(); const open = defineModel<boolean>('open', { default: false }); const emit = defineEmits<{ confirm: [skippedKeys: string[]] }>(); const skippedKeys = shallowRef<Set<string>>(new Set());
const rows = computed(() => (props.preview?.rows ?? []).map((row) => ({ ...row, displayAction: skippedKeys.value.has(row.key) ? 'skip' : row.action })));
const summary = computed(() => ({ createCount: rows.value.filter((row) => row.displayAction === 'create').length, errorCount: rows.value.filter((row) => row.errors.length > 0).length, importableCount: rows.value.filter((row) => row.importable && row.displayAction !== 'skip').length, readCount: rows.value.length, skippedCount: rows.value.filter((row) => row.displayAction === 'skip').length, updateCount: rows.value.filter((row) => row.displayAction === 'update').length }));
watch(() => props.preview?.materialId, () => { skippedKeys.value = new Set(); }); function toggleSkip(row: EnterpriseWorkspaceEmployeeImportPreviewRow) { const next = new Set(skippedKeys.value); if (next.has(row.key)) next.delete(row.key); else next.add(row.key); skippedKeys.value = next; } function actionColor(action: EnterpriseWorkspaceEmployeeImportAction) { return { create: 'green', error: 'red', skip: 'default', update: 'blue' }[action]; } function actionLabel(action: EnterpriseWorkspaceEmployeeImportAction) { return { create: '新增', error: '错误', skip: '跳过', update: '更新' }[action]; } function formatYesNo(value: null | number | undefined) { return value === 1 ? '是' : value === 0 ? '否' : '-'; }
</script>
<template><Modal v-model:open="open" title="员工名册导入预览" width="1060px"><div v-if="preview" class="employee-import-preview"><Alert message="确认前可跳过单行；有错误的行不会写入。已存在的员工将按身份证号或姓名、部门、职位进行更新。" show-icon type="info" /><div class="employee-import-preview__stats"><Statistic title="读取" :value="summary.readCount" /><Statistic title="新增" :value="summary.createCount" /><Statistic title="更新" :value="summary.updateCount" /><Statistic title="可导入" :value="summary.importableCount" /><Statistic title="提示/错误" :value="summary.errorCount" /><Statistic title="跳过" :value="summary.skippedCount" /></div><div class="employee-import-preview__table-wrap"><table class="employee-import-preview__table"><thead><tr><th>行</th><th>结果</th><th>姓名</th><th>部门 / 职位</th><th>科技 / 在职</th><th>提示</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.key"><td>{{ row.rowNumber }}</td><td><Tag :color="actionColor(row.displayAction)">{{ actionLabel(row.displayAction) }}</Tag></td><td>{{ row.data.yg_name || '-' }}</td><td>{{ row.data.department || '-' }} / {{ row.data.position || '-' }}</td><td>{{ formatYesNo(row.data.is_kjyf) }} / {{ formatYesNo(row.data.is_active) }}</td><td><div v-if="row.errors.length" class="employee-import-preview__errors"><span v-for="error in row.errors" :key="`${row.key}-${error.message}`">{{ error.fieldName ? `${error.fieldName}：` : '' }}{{ error.message }}</span></div><span v-else>-</span></td><td><Button v-if="row.importable" size="small" @click="toggleSkip(row)">{{ row.displayAction === 'skip' ? '恢复' : '跳过' }}</Button><span v-else class="employee-import-preview__muted">不可导入</span></td></tr></tbody></table></div></div><template #footer><Button @click="open = false">取消</Button><Button :disabled="summary.importableCount === 0" :loading="loading" type="primary" @click="emit('confirm', [...skippedKeys])">确认导入 {{ summary.importableCount }} 条</Button></template></Modal></template>
<style scoped>.employee-import-preview { display: grid; gap: 16px; }.employee-import-preview__stats { display: grid; grid-template-columns: repeat(6, minmax(0, 1fr)); gap: 12px; padding: 12px; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; }.employee-import-preview__table-wrap { max-height: 480px; overflow: auto; border: 1px solid #e5e7eb; border-radius: 6px; }.employee-import-preview__table { width: 100%; min-width: 900px; border-collapse: collapse; }.employee-import-preview__table th,.employee-import-preview__table td { padding: 10px 12px; text-align: left; vertical-align: top; border-bottom: 1px solid #e5e7eb; }.employee-import-preview__table th { position: sticky; top: 0; z-index: 1; background: #f9fafb; }.employee-import-preview__errors { display: grid; gap: 4px; color: #dc2626; }.employee-import-preview__muted { color: #9ca3af; }@media (max-width: 720px) {.employee-import-preview__stats { grid-template-columns: repeat(2, minmax(0, 1fr)); }}</style>
